import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
const t = new StdioClientTransport({ command: 'node', args: ['/home/gavin/dev/Scidonia/rocq-piler/dist/index.js', '--coq-lsp-path', '/home/gavin/.opam/rocq-9/bin/coq-lsp'] });
const c = new Client({ name: 'test', version: '0' }, { capabilities: {} });
await c.connect(t);
const r = await c.listTools();
const names = r.tools.map(t => t.name);
console.log(names.includes('stratify') ? 'STRATIFY AVAILABLE' : 'stratify NOT in tools');
console.log('Tools:', names.filter(n => n.includes('strat') || n.includes('try') || n.includes('insert')).join(', '));
process.exit(0);
